{{- if and .Values.bucketweb.enabled .Values.bucketweb.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "thanos.bucketweb.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: receive
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "thanos.bucketweb.fullname" . }}
  minReplicas: {{ .Values.bucketweb.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.bucketweb.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.bucketweb.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.bucketweb.autoscaling.targetMemory }}
    {{- end }}
    {{- if .Values.bucketweb.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.bucketweb.autoscaling.targetCPU }}
    {{- end }}
{{- end }}
