{{- if and .Values.storegateway.enabled .Values.storegateway.autoscaling.enabled (not .Values.storegateway.sharded.enabled) }}
apiVersion: apps/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "thanos.storegateway.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: storegateway
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "thanos.storegateway.fullname" . }}
  minReplicas: {{ .Values.storegateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.storegateway.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.storegateway.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.storegateway.autoscaling.targetMemory }}
    {{- end }}
    {{- if .Values.storegateway.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.storegateway.autoscaling.targetCPU }}
    {{- end }}
{{- end }}
