{{ if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.server.name}}-secret
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $conf, $value := .Values.secrets }}
  {{$conf}}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}