apiVersion: v2
appVersion: v3.0.1
description: A Helm chart for Argo Workflows
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
maintainers:
- name: alexec
- name: alexmt
- name: jessesuen
- name: benjaminws
name: argo
version: 0.17.38
